default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: zzx971106
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sudoku_server_development

test:
  <<: *default
  database: sudoku_server_test

production:
  <<: *default
  database: sudoku_server_production
  username: postgres
  password: zzx971106